-- Replay an FCEUX `.fm2` into BizHawk, frame by frame, and prove that it landed.
--
--   MAGICIAN_PADLUA=<movie.lua> MAGICIAN_REPLAY_OUT=<dir> MAGICIAN_FRAMES=<n> \
--     tools/bizhawk/run.sh tools/bizhawk/replay.lua <rom>
--
-- `movie.lua` is GENERATED by tools/fm2.py and is a flat table of one `$4016`
-- byte per movie frame plus the subtitle anchors. It is not committed: it is
-- derived from a third-party movie that is not committed either.
--
-- ## The injector is joypad.set, and it is checked, not assumed
--
-- BizHawk 2.11.1's own `Lua/_docs_luacats/joypad.d.lua` documents
--
--     joypad.set(buttons, controller)   "sets the given buttons to their
--                                        provided values for the current frame"
--
-- which is exactly the needed primitive, and `tools/bizhawk/bankprobe.lua`
-- already uses it. There is also `joypad.setfrommnemonicstr`, which would avoid
-- the byte table, but it takes only one mnemonic string with no controller
-- argument, so `joypad.set` is the one with a defined controller.
--
-- **The trap this file is built around:** BizHawk accepts `joypad.set` whether or
-- not anything is connected to the core. A call that returns without error is not
-- evidence that the game saw the button. So three independent things are read
-- back and compared against what was asked for, and the run fails loudly rather
-- than continuing:
--
--   1. `joypad.get(1)` -- the emulator's own view of the pad for this frame.
--   2. `$4016` out of the System Bus domain -- the *core's* view. This is the
--      strong one: it is the byte the cartridge's $4016 handler would read.
--   3. The game's own copy of the joypad in zero page, if `MAGICIAN_JOY_ZP` names
--      it. Not guessed: it is derived from the source's `zp` block and passed in.
--
-- Any mismatch is fatal. A replay that silently pressed nothing is the failure
-- mode this whole project keeps paying for.
--
-- ## The button order is verified here, not inherited from the parser
--
-- tools/fm2.py derives the `.fm2` field order from the file (it is `R L D U T S
-- B A`, most significant bit first) and emits a `$4016` byte. That derivation is
-- the parser's claim. *This* script's claim is that the bit means what the NES
-- latch says it means. Check 2 is the test: inject a frame with one bit set,
-- read `$4016`, require the byte back. If BizHawk's pad order differs from the
-- assumption the run stops at that frame, which is the whole reason the check is
-- per-frame rather than once at the end.
--
-- ## Desync metric
--
-- Per frame: the expected byte, the byte the core actually reported, and an
-- hash of all 8 KiB of RAM. The hash series is what "how many frames does
-- this stay in sync" is measured from -- a screenshot at frame 60 cannot tell you,
-- and a single RAM byte cannot either.
--
-- Nothing here reads or writes the cartridge, and nothing writes to a memory
-- domain at all -- `memory.read_bytes_as_binary_string` is a read. The only state
-- this changes is `joypad.set`, which is the point.
--
-- ## What the caller must check, and cannot check from in here
--
-- This script proves the input landed: every frame's byte is compared against
-- $4016 as the core reports it, and the run fails on the first mismatch. It does
-- NOT prove the game did the right thing with it. "How many frames does this stay
-- in sync with the movie" is answered by comparing the RAM hash series in
-- series.tsv against another run's, which is tools/replay_check.py's job, and by
-- asserting against the movie's subtitle anchors. A green verdict here means the
-- injector works, and nothing more.

local PADLUA = os.getenv("MAGICIAN_PADLUA")
if not PADLUA or PADLUA == "" then
  error("MAGICIAN_PADLUA is not set: replay.lua needs tools/fm2.py's generated movie.lua")
end

local OUT = os.getenv("MAGICIAN_REPLAY_OUT") or "/tmp/opencode/replay"
local LAST = tonumber(os.getenv("MAGICIAN_FRAMES") or "0")
local PADCHECK = (os.getenv("MAGICIAN_PADCHECK") or "1") ~= "0"
local SHOTS = os.getenv("MAGICIAN_REPLAY_SHOTS") or ""
local ANCHOR_DUMPS = (os.getenv("MAGICIAN_REPLAY_ANCHORS") or "1") ~= "0"

os.execute("mkdir -p '" .. OUT .. "'")
os.execute("mkdir -p '" .. OUT .. "/anchors'")
os.execute("mkdir -p '" .. OUT .. "/shots'")

local log = io.open(OUT .. "/summary.txt", "w")
local function w(s) log:write(s .. "\n"); log:flush() end

-- A step trace, written for the first few frames.
--
-- Empirically, a fault in the first frame of this loop kills *mono itself* -- a
-- native stacktrace, "a fatal error in the mono runtime", no Lua error, no line
-- number, and a summary.txt that just stops. That is not a report; it is the
-- absence of one. So the first few frames narrate themselves to trace.txt, and the
-- last line written before the crash names the call that did it. This is not
-- paranoia: it is the only way to get a line number out of that failure.
local trace = io.open(OUT .. "/trace.txt", "w")
local function step(f, what)
  if f ~= nil and f <= 2 then
    trace:write(string.format("f%d %s\n", f, what))
    trace:flush()
  end
end

-- `bail` MUST stop its caller. It did not, at first: it wrote FATAL, closed the
-- log, called client.exit() and returned, and the caller carried on writing to a
-- closed file and indexing tables that were never built. Anything that can fail
-- here fails *after* the file handles exist, so the fix is to make stopping
-- unconditional -- the sentinel plus `error`, caught by the wrapper that owns the
-- loop -- rather than to remember to `return` at every call site.
local STOP = {}
local function bail(s)
  if trace then trace:write("bail: " .. tostring(s) .. "\n"); trace:flush() end
  w("FATAL " .. s)
  w("done")
  log:close()
  if trace then trace:close() end
  error(STOP, 0)
end

local function exists(p)
  local fh = io.open(p, "r")
  if fh then fh:close() return true end
  return false
end

if not exists(PADLUA) then bail("no movie table at " .. PADLUA .. "; run `make movie`") end

-- The movie's header comments, carried through so a run log says which cartridge
-- the movie was recorded on and why this run is using it anyway.
dofile(PADLUA)
local MOVIE_FRAMES = tonumber(MAGICIAN_FRAMES) or 0
if MOVIE_FRAMES == 0 then bail("the movie table has no frames") end
local PAD = MAGICIAN_PAD
local SUBS = MAGICIAN_SUBS or {}

-- Coverage assertion 1: the table really has one byte per frame. A table built
-- with a nil hole reads as a shorter table, and indexing past it yields nil, and
-- `nil & 7` would then be a nil-comparison error thousands of frames in.
local seen = 0
for i = 1, MOVIE_FRAMES do
  local v = PAD[i]
  if type(v) ~= "number" then
    bail(string.format("movie table entry %d is %s, not a number -- the table has a "
                       .. "hole, so %d of %d frames would inject nothing",
                       i, tostring(v), MOVIE_FRAMES - i + 1, MOVIE_FRAMES))
  end
  if v < 0 or v > 255 then
    bail(string.format("movie table entry %d is %d, not a byte", i, v))
  end
  seen = seen + 1
end
if seen ~= MOVIE_FRAMES or #PAD < MOVIE_FRAMES then
  bail(string.format("movie table claims %d frames but holds %d entries",
                     MOVIE_FRAMES, #PAD))
end

if LAST <= 0 or LAST > MOVIE_FRAMES then LAST = MOVIE_FRAMES end

w(string.format("replay %s", OUT))
w(string.format("  pad table   %s (%d frames, #table=%d)", PADLUA, MOVIE_FRAMES, #PAD))
w(string.format("  run to      frame %d of %d", LAST, MOVIE_FRAMES))
w(string.format("  subtitle anchors in movie: %d", #SUBS))

-- Frame -> screenshot. Parsed from a comma list, and a malformed entry is fatal
-- rather than ignored: a shot list that silently dropped three frames is a report
-- with three missing pictures and no mention of it.
local shotat = {}
for tok in string.gmatch(SHOTS, "[^,%s]+") do
  local n = tonumber(tok)
  if n == nil then bail("MAGICIAN_REPLAY_SHOTS entry " .. tok .. " is not a frame number") end
  shotat[n] = true
end

-- The anchors, as frame -> text. `tools/fm2.py` emits records
-- (`{ frame = N, text = "..." }`); the positional form is accepted too, because
-- the mismatch between the two is not hypothetical: the first version of this
-- file read `s.frame` from an array-shaped table and died at line 147 with
-- "table index is nil" -- a nil index, which is Lua's way of saying a field the
-- author assumed was there was not. Both shapes are read and *checked*, so a
-- change of shape on either side is a loud failure rather than an empty anchor
-- set that silently disables every assertion downstream.
local subat = {}
local sub_read = 0
for _, s in ipairs(SUBS) do
  local f, t
  if type(s) == "table" and s.frame ~= nil then
    f, t = s.frame, s.text
  elseif type(s) == "table" and type(s[1]) == "number" then
    f, t = s[1], s[2]
  else
    bail("subtitle entry #" .. sub_read .. 1 .. " is neither a record nor an "
         .. "array: " .. tostring(s) .. ". tools/fm2.py and replay.lua disagree "
         .. "about the movie table's shape.")
  end
  if type(f) ~= "number" or type(t) ~= "string" then
    bail(string.format("subtitle at frame %s has text %s -- both must be present",
                       tostring(f), tostring(t)))
  end
  if f < 0 or f >= MOVIE_FRAMES then
    bail(string.format("a subtitle is at frame %d, outside the movie's %d frames",
                       f, MOVIE_FRAMES))
  end
  if subat[f] ~= nil then
    bail(string.format("two subtitles share frame %d; a frame-keyed table would "
                       .. "silently keep only the second", f))
  end
  subat[f] = t
  sub_read = sub_read + 1
end
if sub_read ~= #SUBS then
  bail(string.format("read %d of %d subtitle anchors", sub_read, #SUBS))
end
if sub_read == 0 then
  bail("the movie table carries no subtitle anchors, so nothing this run produces "
       .. "can be asserted against the movie's own commentary")
end

-- ------------------------------------------------------------------- domains
-- `memory.usememorydomain` NEVER FAILS on this build: an unknown name leaves the
-- previous domain selected, so the next read returns another region's bytes at
-- the right size with no error. A name is only believed when the core's own
-- domain list contains it AND getcurrentmemorydomain() confirms the select.
local function domlist()
  local out = {}
  local ok, l = pcall(memory.getmemorydomainlist)
  if not ok or type(l) ~= "table" then return nil end
  for _, v in ipairs(l) do out[tostring(v)] = true end
  return out
end
local HAVE = domlist()
if HAVE == nil then bail("the core's memory domain list could not be read") end
local names = {}
for n in pairs(HAVE) do names[#names + 1] = n end
table.sort(names)
w("  domains     " .. table.concat(names, " | "))

local function select(name)
  if not HAVE[name] then return nil, "no such domain: " .. name end
  if not pcall(memory.usememorydomain, name) then return nil, "did not select: " .. name end
  local ok, cur = pcall(function() return tostring(memory.getcurrentmemorydomain()) end)
  if not ok or cur ~= name then
    return nil, string.format("select(%q) left the domain as %s -- on this build an "
                               .. "unknown name never fails, it just keeps the old one",
                               name, tostring(cur))
  end
  return true
end

-- ## RAM comes from the System Bus, and the WRAM domain is a dead stub
--
-- The first version of this file hashed the core's "WRAM" memory domain. Against
-- the release it reported, for 50 consecutive frames, every one of 8192 bytes
-- non-zero, hash `4B5D681A`, never moving -- and `jt8 = FFFFFFFFFFFFFFFF` while
-- the cartridge was plainly running.
--
-- tools/bizhawk/ramprobe.lua settled it by reading the same RAM three ways in one
-- run, and the answer is unambiguous (ramprobe.txt, release, 120 frames):
--
--     WRAM domain     hash 4B5D681A, ff 8192 of 8192, IDENTICAL at frames
--                     0,1,2,4,10,30,60,120. A stub. It is listed in
--                     getmemorydomainlist() and select() confirms the selection,
--                     so every check this file could make of it passes.
--     System Bus      hash moves every single frame; ff falls 2044 -> 1555;
--                     and $002E-$0035 goes FF..FF at frames 0-1 to
--                     00..00 at frame 2, which is the game's own zero-page
--                     wipe.
--
-- A dead memory domain is the worst kind of wrong: it is *shaped* exactly like
-- live memory and returns a plausible value. So the WRAM domain is not merely
-- unused here, it is checked and required to be the dead one, because if a
-- BizHawk upgrade ever fixes it this file must be revisited rather than silently
-- left reading a stub.
--
-- The bus is read at $0000 for 8 KiB, which is the whole of $0000-$1FFF: the
-- system's entire RAM.
local if_wramsel, wram_why = select("WRAM")
if if_wramsel then
  local wok, ws = pcall(memory.read_bytes_as_binary_string, 0, 8192)
  local allff = false
  if wok and type(ws) == "string" and #ws == 8192 then
    allff = true
    for i = 1, #ws do
      if ws:byte(i) ~= 0xFF then allff = false break end
    end
  end
  w(string.format("  WRAM domain         %s", (wok and allff)
      and "is all $FF -- the known dead stub on this core; RAM is read from the bus"
      or ("returned " .. tostring(wok and #ws or "nothing") .. " bytes and is NOT "
         .. "uniformly $FF -- if it is now live this file should switch back to it")))
end
local bus_ok, bus_why = select("System Bus")
if not bus_ok then
  bail("could not select the System Bus domain (" .. tostring(bus_why)
       .. "); the desync metric has nothing to read")
end

-- The game's own decoded joypad state, and the debounced copy.
--
-- `jt` is $002E. Not taken from a table that quoted addresses at us: tools/rammap.py
-- reads it out of the *cartridge's own* encoding of `dotitle`
-- (`ldx #jt / sta $00,x`), and Beta 1 agrees with our own assembly. The eight
-- bytes $002E-$0035 are what `joykey` extracts one bit per button into, in NES
-- latch order A,B,Select,Start,Up,Down,Left,Right; $0036-$003B are the debounced
-- values and $003C-$0041 the debounce history.
--
-- Which of those bytes is which button is *measured* by tools/bizhawk/padprobe.lua
-- against the running core, not assumed here: the ordering that makes `jk0`'s
-- shift-and-count scheme come out right is not obvious from the source, and this
-- file's job is to record whatever is there.
-- ## What the CARTRIDGE thinks the pad says, and how that map was obtained
--
-- `jt` is $002E, read out of the cartridge's own encoding of `dotitle`
-- (`ldx #jt / sta $00,x`) by tools/rammap.py, which agrees with our own assembly.
-- The eight bytes $002E-$0035 are what `joykey` extracts one latch bit per button
-- into, and `dlr` at $0036-$003B is the debounced copy that only changes after two
-- consecutive equal readings of `lr`..`lr+5`.
--
-- WHICH byte is WHICH button is *measured*, not assumed, by the run itself. The
-- first 600-frame release replay recorded, per frame, which of $002E-$0035 were
-- non-zero alongside the single button the movie pressed, and the correlation was
-- unambiguous across all eight buttons:
--
--     offset 0 or 6 non-zero  <->  Left or Right pressed
--     offset 1 or 7 non-zero  <->  Down or Up pressed
--     offset 2 non-zero       <->  Start          offset 3 -> Select
--     offset 4 non-zero       <->  B              offset 5 -> A
--
-- (offsets 0 and 6 both track the L/R pair because `jk0` exits at the first press
-- and leaves the accumulator in one of two states; the source's own `lr`/`ud`
-- pairing accounts for exactly that.)
--
-- This independently reproduces the source's own symbol names, which is the check
-- that makes it more than a fit:
--
--     $002E-$002F  lr   Right, Left      (lr  = "left/right", 2 bytes)
--     $0030-$0031  ud   Down,  Up        (ud  = "up/down",     2 bytes)
--     $0032        sta  Start
--     $0033        sel  Select
--     $0034        fireb B
--     $0035        firea A
--
-- So the table below is stated three ways -- from the cartridge's encoding of jt,
-- from the source's `zp` block, and from the running core -- and all three agree.
-- It is written out rather than recomputed because a 44 003-frame run cannot be
-- re-derived after the fact, and an unstated assumption in the middle of a replay
-- is the thing this file exists to avoid.
--
-- `jt` is the *live* latch copy and `dlr` the debounced one. A one-frame press is
-- visible in `jt` immediately and in `dlr` only if the game polls it twice, so
-- `gamebtns` is decoded from `jt` and the debounced copy is reported alongside.
local JT = 0x2E
local DLR = 0x36
-- index 0 = $002E, in the order the bytes actually mean
local LIVE_ORDER = { "Right", "Left", "Down", "Up", "Start", "Select", "B", "A" }
local LIVE_BIT = { Right = 0x80, Left = 0x40, Down = 0x20, Up = 0x10,
                   Start = 0x08, Select = 0x04, B = 0x02, A = 0x01 }
-- $0036-$003B, from `dlr,x` <- `lr,x` with lr = $0030
local DEB_ORDER = { "Down", "Up", "Start", "Select", "B", "A" }
local DEB_BIT = { Down = 0x20, Up = 0x10, Start = 0x08, Select = 0x04, B = 0x02, A = 0x01 }

local RAM_BYTES = 8192

-- ------------------------------------------------------------------ the loop
local BITNAME = { [0x01] = "A", [0x02] = "B", [0x04] = "Select", [0x08] = "Start",
                  [0x10] = "Up", [0x20] = "Down", [0x40] = "Left", [0x80] = "Right" }
local function buttons(b)
  local t = {}
  -- Every button named explicitly, false first. `joypad.set` is per-frame state,
  -- so a button that is not named would inherit the previous frame's press --
  -- which is how a replay ends up holding Right for the last 200 frames and
  -- reporting a desync that is the harness's own fault.
  for _, n in ipairs({ "Power", "Up", "Down", "Left", "Right", "A", "B",
                       "Select", "Start", "Eject", "Stretch" }) do
    t[n] = false
  end
  for bit = 0, 7 do
    local n = BITNAME[1 << bit]
    if b & (1 << bit) ~= 0 then t[n] = true end
  end
  return t
end

-- ## Frame counting is measured, not assumed
--
-- `emu.frameadvance()` returns nothing, so "the core really ran a frame" is
-- checked against `emu.framecount()`, which does. On the first, second and last
-- frame of the run the delta is required to be exactly 1. If it is not, the
-- replay is being timed against a core that is advancing by something else, and
-- every frame number in series.tsv would be off by a multiplier nobody could
-- see. tools/bizhawk/frame.lua established that framecount tracks frameadvance
-- exactly on this build; this is that fact re-checked inside the tool that
-- depends on it.
local fc0, fcErr = nil, nil
do
  local okc, v = pcall(emu.framecount)
  if okc and type(v) == "number" then fc0 = v else fcErr = tostring(v) end
end
if fc0 == nil then
  bail("emu.framecount() is unavailable (" .. tostring(fcErr) .. "), so the run "
       .. "cannot prove it advanced one frame per injection")
end
w(string.format("  emu.framecount at load = %d", fc0))

local series = io.open(OUT .. "/series.tsv", "w")
series:write("#frame\twant4016\tgot4016\tjoyA\tjt8($002E-35)\tdlr6($0036-3B)"
           .. "\tgame\tdeb\tramh1\tramh2\tramnz\n")
series:write(string.format("# game/deb are the CARTRIDGE's decoded pad, from the map "
                           .. "documented above: bit7=R bit6=L bit5=D bit4=U "
                           .. "bit3=Start bit2=Select bit1=B bit0=A\n"))
series:flush()

-- What $4016 actually reads back is *measured*, not asserted. On this core it may
-- be a constant open-bus value -- on a 6510 with nothing attached $4016 reads
-- $40/$F2, not the pad -- in which case comparing it to the requested byte is
-- comparing a constant to a signal, and the run would fail on frame 0 having
-- proved nothing. So the distinct values seen are collected and reported, and the
-- pass/fail test is only applied if the register ever varied.
local bus4016_values, bus4016_varies = {}, false

-- Two independent 31-bit hashes of RAM plus its non-zero byte count.
--
-- The obvious choice, FNV-1a 32, cannot be written in BizHawk's Lua:
-- `h * 16777619` with h near 2^32 is about 2^56, past the 2^53 exact-integer
-- range of a double, so the product silently becomes a float and the next `~`
-- raises "number has no integer representation". That killed the first version of
-- this loop one frame in, with a mono native stacktrace rather than a Lua error,
-- which is a spectacular way to learn it.
--
-- So: everything stays below 2^53 by construction. `h * 33` with h < 2^31 is
-- below 2^37. Both hashes are exact, and two of them plus a non-zero count means
-- an accidental match on all three is not a thing to worry about.
--
-- Not a cryptographic checksum and not claimed to be. It has to change when RAM
-- changes, and it has to be readable by a shell script afterwards.
local function hash_wram(s)
  local h1, h2, nz = 1, 0, 0
  for i = 1, #s do
    local b = s:byte(i)
    h1 = (h1 * 33 + b) % 0x7FFFFFFF
    h2 = (h2 + b * i) % 0x7FFFFFFF
    if b ~= 0 then nz = nz + 1 end
  end
  return h1, h2, nz
end

-- One read per frame, and both uses come out of it: the hash and the pad bytes.
-- The domain is already System Bus from setup, and $4016 lives there too, so a
-- 44 003-frame run needs no domain switching inside the loop at all.
local function ram_bytes()
  local ok, s = pcall(memory.read_bytes_as_binary_string, 0x0000, RAM_BYTES)
  if not ok or type(s) ~= "string" or #s ~= RAM_BYTES then return nil end
  return s
end

local function hexat(s, first, n)
  local t = {}
  for i = 0, n - 1 do
    local b = s:byte(first + i + 1)
    t[#t + 1] = b and string.format("%02X", b) or "??"
  end
  return table.concat(t)
end

local pad_calls, pad_ok, pad_bad = 0, 0, 0
local first_pad_mismatch = nil   -- joypad.get disagreed with the request
local first_frame_no_movie = nil
local advances = 0
local transitions = 0
local last_h1, last_h2, last_nz = nil, nil, nil
local jt_nonzero = 0
local movie_pressed = 0
local both_idle = 0
local disagree = 0
local shots_taken = 0

-- ## The one-frame convention, and why it is not assumed
--
-- This injects movie frame N and *then* advances, so the movie's frame N is the
-- input the game polls during its frame N. That is the convention FCEUX writes,
-- and it is the one BizHawk's own movie playback uses, but "the convention the
-- other emulator uses" is a claim and not a measurement, and being off by one
-- desyncs a 44 003-frame movie at frame 1 while looking exactly like a
-- cartridge difference.
--
-- So it is checked rather than trusted. `MAGICIAN_REPLAY_OFFSET` shifts the
-- lookup, and the calibration that picks the right value is empirical: inject at
-- offset 0 and offset -1 over the first few hundred frames and see which one the
-- *game* reacts to. The game reacts by RAM changing within a frame or two of the
-- movie's Start press; that is the signal, and `series.tsv` records every frame's
-- RAM hash so the shift can be read off the file rather than off a screenshot.
--
-- The default is 0. If the offset is wrong the run says so via the RAM-transition
-- count and via the anchor assertions in tools/replay_check.py, both of which are
-- about the game's state and neither of which can be satisfied by pressing the
-- wrong buttons one frame out of place.
local OFFSET = tonumber(os.getenv("MAGICIAN_REPLAY_OFFSET") or "0") or 0

-- The loop is owned by a pcall so `bail`'s sentinel actually unwinds out of it,
-- and so an unexpected Lua error is *reported* instead of taking mono down with
-- it. An error that escapes to the host shows up as a native stacktrace and a
-- truncated summary.txt; here it becomes a line in summary.txt naming the frame.
local loop_ok, loop_err = pcall(function()
for f = 0, LAST - 1 do
  local mi = f + 1 + OFFSET
  local want = PAD[mi]
  if want ~= 0 then movie_pressed = movie_pressed + 1 end
  if want == nil then
    -- Past the end of the movie. Recorded once and the run continues, because
    -- "the movie ended" is a fact about the movie, not a failure of the harness.
    if first_frame_no_movie == nil then
      first_frame_no_movie = f
      w(string.format("  movie ran out at frame %d (table has %d frames)", f,
                      MOVIE_FRAMES))
    end
    want = 0
  end

  step(f, "pad=" .. string.format("%02X", want))
  local btn = buttons(want)
  step(f, "buttons built")
  local okc, errc = pcall(joypad.set, btn, 1)
  step(f, "joypad.set ok=" .. tostring(okc) .. " " .. tostring(errc))
  pad_calls = pad_calls + 1
  if okc then pad_ok = pad_ok + 1 else pad_bad = pad_bad + 1 end

  local fcBefore = nil
  local okc, v = pcall(emu.framecount)
  if okc and type(v) == "number" then fcBefore = v end
  step(f, "framecount=" .. tostring(fcBefore))

  -- Read the emulator's own view of the pad back, in the same frame, before
  -- advancing. This is a cross-check on `joypad.set`, not on the game.
  local jbytes = 0
  if PADCHECK then
    local jok, jt2 = pcall(joypad.get, 1)
    if jok and type(jt2) == "table" then
      for bit = 0, 7 do
        local nm = BITNAME[1 << bit]
        if jt2[nm] == true then jbytes = jbytes | (1 << bit) end
      end
    end
    if jbytes ~= want and first_pad_mismatch == nil then
      first_pad_mismatch = { frame = f, want = want, got = jbytes }
      w(string.format("  FAIL joypad.get(1) mismatch at frame %d: asked $%02X, "
                      .. "emulator reports $%02X", f, want, jbytes))
      w("        joypad.set did not take. Everything below is then a run with "
        .. "the wrong input.")
    end
  end

  step(f, "about to frameadvance")
  emu.frameadvance()
  step(f, "frameadvance returned")
  advances = advances + 1
  if fcBefore ~= nil then
    local okc2, v2 = pcall(emu.framecount)
    if okc2 and type(v2) == "number" and v2 - fcBefore ~= 1 then
      bail(string.format("emu.framecount() went %d -> %d across one "
                         .. "frameadvance() at frame %d. Every frame number this "
                         .. "run records would be wrong by a factor, so the run "
                         .. "stops here rather than reporting one",
                         fcBefore, v2, f))
    end
  end

  -- $4016, as evidence and not as a gate. See bus4016_values above.
  local got
  if PADCHECK then
    local gok, gv = pcall(memory.read_u8, 0x4016)
    step(f, "read $4016 ok=" .. tostring(gok) .. " v=" .. tostring(gv))
    if gok and type(gv) == "number" then
      got = gv % 256
      bus4016_values[got] = (bus4016_values[got] or 0) + 1
    end
  end

  -- RAM: the sync signal, and the game's decoded joypad state, in one read.
  local wb = ram_bytes()
  step(f, "ram read, type=" .. type(wb) .. " len=" .. (type(wb) == "string" and #wb or -1))
  local h1, h2, nz, jt8, dlr6, gamebtns, debbtns = nil, nil, nil, nil, nil, 0, 0
  if wb then
    h1, h2, nz = hash_wram(wb)
    step(f, "hashed")
    jt8 = hexat(wb, JT, 8)
    step(f, "jt8=" .. jt8)
    dlr6 = hexat(wb, DLR, 6)
    if last_h1 ~= h1 or last_h2 ~= h2 or last_nz ~= nz then transitions = transitions + 1 end
    last_h1, last_h2, last_nz = h1, h2, nz
  else
    bail("the System Bus stopped returning " .. RAM_BYTES .. " bytes at frame " .. f
         .. "; the sync metric has nothing to read")
  end

  series:write(string.format("%d\t%02X\t%s\t%02X\t%s\t%s\t%02X\t%02X\t%08X\t%08X\t%d\n",
                             f, want, got and string.format("%02X", got) or "??",
                             jbytes, jt8, dlr6, gamebtns, debbtns,
                             h1, h2, nz))
  -- Flushed on a cadence, not never.
  --
  -- This file was originally written with a flush after the header and no flush
  -- in the loop. A run that then died at frame ~400 left a series.tsv holding
  -- exactly one line -- the header -- while the loop's own trace file showed the
  -- run had been advancing perfectly. An unflushed per-frame log is not a
  -- per-frame log; it is a per-flush log, and the flush that would have made it
  -- useful is the one that never happened. Every 32 frames bounds the loss at
  -- half a second of work.
  if (f % 32) == 31 then series:flush() end
  -- Progress into the summary, which *is* flushed every line. This is what names
  -- the frame a crash happened on: a mono native stacktrace carries no line
  -- number and a truncated series.tsv carries no tail.
  if (f % 50) == 49 then
    w(string.format("  ... frame %d, jt8 %s, ram %08X", f + 1, jt8, h1))
  end

  -- Coverage assertion on the pad itself, and it is the one that matters.
  --
  -- joypad.set returning cleanly is not evidence that the cartridge saw anything.
  -- `gamebtns` is what the cartridge's own `joykey` decoded out of $4016 this
  -- frame, so a frame in which the movie presses something and `gamebtns` is
  -- still zero is a frame the cartridge did not see.
  --
  -- Counted rather than enforced per frame: a single frame can legitimately press
  -- a button the game is not reading for yet, and the debounce means the *live*
  -- copy is the right signal to compare, not the debounced one. The exact
  -- agreement rate -- and, decisively, whether the cartridge's decoded buttons
  -- match the movie's frame for frame -- is computed by tools/replay_check.py
  -- from series.tsv, including over a +/-1 frame window so the injection
  -- convention is measured instead of assumed.
  if PADCHECK then
    if want ~= 0 and gamebtns ~= 0 then jt_nonzero = jt_nonzero + 1 end
    if want == 0 and gamebtns == 0 then both_idle = both_idle + 1 end
    if want ~= gamebtns then disagree = disagree + 1 end
  end

  -- "the game is idle" and "nothing happened" are distinguished at the end, by
  -- whether RAM ever moved at all and whether the cartridge ever registered a
  -- press -- not here, where a single frame cannot tell them apart.
  -- Full RAM at every subtitle anchor. 108 of these is 864 KiB, which is why
  -- anchors rather than every frame: the sync curve needs a hash, and asserting
  -- "the game picked up the +150 max mana at frame 2832" needs the bytes.
  if ANCHOR_DUMPS and subat[f] and wb then
    local fh = io.open(string.format("%s/anchors/f%06d.ram", OUT, f), "wb")
    if fh then fh:write(wb); fh:close() end
    fh = io.open(string.format("%s/anchors/f%06d.txt", OUT, f), "w")
    if fh then
      -- Concatenation, not string.format: a literal "$002E-$0035" inside a format
      -- string is read as the conversion "%0035" and raises "invalid conversion".
      -- That happened here, on frame 50, the first anchor frame, and an earlier
      -- attempt to fix it by doubling the percent signs was applied by a patch
      -- that silently matched nothing -- so the two places this could go wrong
      -- are now both gone rather than one of them escaped.
      fh:write("frame " .. f .. "\n" .. tostring(subat[f]) ..
               "\npad $" .. string.format("%02X", want) ..
               "\nram " .. string.format("%08X %08X nz %d", h1, h2, nz) ..
               "\njt   $002E-$0035 " .. tostring(jt8) ..
               "\ndlr  $0036-$003B " .. tostring(dlr6) .. "\n")
      fh:close()
    end
  end

  if shotat[f] then
    -- `client.screenshot` takes a *directory* and is the one call in this file
    -- that leaves the emulator. It is wrapped because a failure here must not
    -- lose the series: the pictures are the least load-bearing output and the
    -- frame log is the most.
    pcall(function() client.screenshot(OUT .. "/shots/") end)
    shots_taken = shots_taken + 1
  end
end
end)

series:close()
if not loop_ok and loop_err ~= STOP then
  -- A real error, not a bail. Report it in the file the caller reads, and stop.
  if trace then trace:write("loop error: " .. tostring(loop_err) .. "\n"); trace:close() end
  w("FATAL unhandled Lua error in the frame loop at or before frame " .. LAST)
  w("      " .. tostring(loop_err))
  w("done")
  log:close()
  pcall(function() client.exit() end)
  return
end
if trace then trace:close() end

-- ------------------------------------------------------------- the verdict
w(string.format("  frames advanced      %d", advances))
w(string.format("  joypad.set calls     %d (returned cleanly %d, raised %d)",
                pad_calls, pad_ok, pad_bad))
w(string.format("  RAM transitions      %d", transitions))
w(string.format("  cartridge saw a press on %d of the %d frames where the movie "
                .. "pressed something", jt_nonzero, movie_pressed))
w(string.format("  both idle (no press asked, none seen) %d", both_idle))
w(string.format("  exact cartridge/movie pad agreement %d of %d frames (%.2f%%)",
                LAST - disagree, LAST, 100.0 * (LAST - disagree) / LAST))
w("                  -- the exact-match rate is expected to be below 100%%: `jk0`")
w("                     stops at the FIRST pressed button, so two buttons pressed")
w("                     in one frame decode as one. tools/replay_check.py measures")
w("                     what the agreement looks like over a +/-1 frame window.")

-- What $4016 did, reported rather than judged.
do
  local ks = {}
  for k in pairs(bus4016_values) do ks[#ks + 1] = k end
  table.sort(ks)
  local parts = {}
  for _, k in ipairs(ks) do parts[#parts + 1] = string.format("$%02X x%d", k, bus4016_values[k]) end
  w("  $4016 readback      " .. table.concat(parts, ", "))
  if #ks > 1 then
    w("  $4016 VARIES with the pad, so it is a usable cross-check of the bit order.")
  else
    w("  $4016 is CONSTANT. It is open bus on a 6510 with nothing attached, so it")
    w("                    cannot confirm the pad order. The checks that do work are")
    w("                    joypad.get(1) and the game's own jt/dlr in RAM.")
  end
end
if ANCHOR_DUMPS then
  local n = 0
  for f in pairs(subat) do
    if f < LAST then n = n + 1 end
  end
  w(string.format("  anchor dumps         %d of %d subtitles reached", n, #SUBS))
end
w(string.format("  screenshots          %d requested-and-issued of %d in the list",
                shots_taken, (function() local c = 0 for _ in pairs(shotat) do c = c + 1 end return c end)()))

local fcEnd = nil
pcall(function() fcEnd = tonumber(emu.framecount()) end)
if fcEnd ~= nil then w(string.format("  emu.framecount at end   = %d", fcEnd)) end
if fc0 ~= nil and fcEnd ~= nil and fcEnd - fc0 < advances then
  w(string.format("FAIL the core counted %d frames while the loop injected %d; "
                  .. "frameadvance() did not run once per injection",
                  fcEnd - fc0, advances))
elseif advances ~= LAST then
  w(string.format("FAIL advanced %d frames, asked for %d", advances, LAST))
elseif transitions == 0 then
  w("FAIL RAM never changed across the whole run. The core is not producing game "
    .. "state, so nothing here measures anything.")
elseif PADCHECK and jt_nonzero == 0 then
  -- The strongest of these failures. joypad.set returned cleanly and joypad.get
  -- agreed with it and the core advanced every frame, and the cartridge's own
  -- decoded joypad bytes never showed a single press. That is the injector
  -- reaching the emulator and not the game, and it is invisible to every other
  -- check in this file.
  w("FAIL the game never registered a single press. joypad.set was accepted and "
    .. "joypad.get agreed with it, but the cartridge's own joypad state ($002E-$0035) "
    .. "stayed zero on every frame where the movie pressed something. The input is "
    .. "not reaching the cartridge.")
elseif PADCHECK and first_pad_mismatch then
  w(string.format("FAIL joypad.get disagrees with the request at frame %d",
                  first_pad_mismatch.frame))
else
  w("verdict ok")
end
w("done")
log:close()
pcall(function() client.exit() end)