#!/usr/bin/env python3
"""Write src/play/zpmap.txt from the assembler's own symbol file.

    python3 tools/genzpmap.py            # regenerate the committed table
    python3 tools/genzpmap.py --check    # fail if the committed table is stale

WHY THIS FILE EXISTS
--------------------
`src/play/ram.py` must be able to say that every address it uses is the address
the assembler gave that name. That claim needs `asm/out/mag.sym`, which is build
output and gitignored, so a suite that reads it cannot run before a build.

So the table is committed as data -- the zero-page and working-RAM part of
mag.sym, name = $address, with a header saying exactly how it was made -- and
`--check` is what keeps it honest. It is the same arrangement as
`asm/patches.manifest`: a derived claim, checked against its source, with the
source able to regenerate it.

WHAT IT IS NOT
--------------
It is not a hand-typed RAM map. Every line comes out of `asm/out/mag.sym`, which
comes out of the assembler, which came out of Eurocom's source. Nothing here is
from a speedrun forum, a video, or a guess.

Note that mag.sym holds several DIFFERENT NAMES for the same address -- the
source links eight modules into one image and each has its own zp block, so
`phase` ($005F) and `l4c` ($005F) are the same byte with the meaning of whichever
module the author was in. Both are kept; picking one is ram.py's job and it has
to justify it.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SYM = ROOT / "asm" / "out" / "mag.sym"
OUT = ROOT / "src" / "play" / "zpmap.txt"

HEADER = """\
# Zero-page and working-RAM symbol map for The Magician rebuild.
#
# GENERATED by tools/genzpmap.py from asm/out/mag.sym -- do not hand-edit.
# Regenerate: python3 tools/genzpmap.py     Verify: python3 tools/genzpmap.py --check
#
# Format: <name> = $<addr>. Address range: $0000-$07FF, which is the whole of the
# game's RAM (`x0.pds:522`: "** Unexpanded RAM $0000-$07FF **").
#
# Several names can share an address: the eight source modules each carry their
# own zero-page block and are linked into one image, so a name only has a
# meaning relative to the module that used it. Where that matters, ram.py records
# the meaning it chose and the evidence for it.
"""


def parse(text: str) -> dict[int, list[str]]:
    out: dict[int, list[str]] = {}
    for line in text.splitlines():
        m = re.match(r"^(\S+)\s*=\s*\$([0-9A-Fa-f]{1,4})\s*$", line)
        if not m:
            continue
        name, addr = m.group(1), int(m.group(2), 16)
        # `a05|!b` is a macro-local label: it exists only inside its own
        # macro's expansion and means nothing to a runtime decoder.
        if "|" in name:
            continue
        if addr > 0x07FF:
            continue
        out.setdefault(addr, []).append(name)
    return out


def render(sym: dict[int, list[str]]) -> str:
    body = [HEADER]
    for addr in sorted(sym):
        for name in sym[addr]:
            body.append(f"{name} = ${addr:04X}")
    return "\n".join(body) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed table is not what mag.sym says")
    args = ap.parse_args()
    if not SYM.exists():
        print(f"genzpmap: no {SYM.relative_to(ROOT)} -- run `make assemble` first")
        return 2
    want = render(parse(SYM.read_text(encoding="latin-1")))
    if args.check:
        if not OUT.exists():
            print(f"genzpmap: {OUT.relative_to(ROOT)} does not exist")
            return 1
        got = OUT.read_text(encoding="utf-8")
        if got != want:
            print(f"genzpmap: {OUT.relative_to(ROOT)} is stale -- "
                  "run `python3 tools/genzpmap.py`")
            return 1
        print(f"genzpmap: {OUT.relative_to(ROOT)} matches {SYM.relative_to(ROOT)}")
        return 0
    OUT.write_text(want, encoding="utf-8")
    n = sum(1 for l in want.splitlines() if not l.startswith("#"))
    print(f"genzpmap: wrote {n} symbols to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())